server:
  port: 8088

spring:
  application:
    name: gamification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/wydad_gamification
    username: wydad_user
    password: wydad_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
